table dim_pizza
	lineageTag: e33ebbfa-2e03-440d-912b-06cbc78bc4c1

	column pizza_id
		dataType: string
		lineageTag: a419d021-0a56-47d2-a80c-5d001139fdcd
		summarizeBy: none
		sourceColumn: pizza_id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 7c70b227-a7e3-4952-bb04-b702039a73e8
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column 'Pizza Category'
		dataType: string
		lineageTag: 8df9c2c5-4a46-462a-9392-73c2c6bfa730
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	partition dim_pizza = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Download\data_pizza.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"pizza_id", type text}, {"name", type text}, {"category", type text}}),
				    #"Selected Columns" = Table.SelectColumns(#"Changed Type",{"pizza_id", "name", "category"}),
				    #"Removed Duplicates" = Table.Distinct(#"Selected Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation PBI_Id = 4b771687007047a78c877d16f857f046
